Image Caching
Jordan141/articleblog pull request #296
Opened 2021-01-21 18:12 UTC by Jordan141

fixes #198

2021-01-21 19:18 UTC, michaelKurowski requested changes

2021-01-21 19:18 UTC, michaelKurowski commented on app/app.js
> +    res.set('Cache-Control', 'public', 'max-age=0, must-revalidate')
Did you test whether it works?

2021-01-21 19:18 UTC, michaelKurowski commented on app/app.js
> +    res.set('Cache-Control', 'public', 'max-age=0, must-revalidate')
You can change category image to check

2021-01-24 16:18 UTC, michaelKurowski commented
I've came up with a solution that wouldn't even need http request if anything.
When you create a link for an image, before adding it to mongo, you just add `?version=checksumOfImage`.
It's just that, the content is cached per url, despite the fact that this param won't be doing anything, it will change url, if the content of the image will change, forcing browser to download new image and cache the new version.
@Jordan141

2021-01-25 15:30 UTC, Jordan141 commented
Fixes #297

2021-01-27 17:20 UTC, michaelKurowski commented
Is the website still working properly? 
You cached all endpoints which means that all responses from server might be ignored by browser

2021-01-30 17:18 UTC, merged